apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-0
spec:
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: prometheus-0-prometheus-prometheus-pryon-kube-prom-prometheus-0
    namespace: prometheus
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/k8s-volumes/prometheus-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - R760xa3hn
